# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2025 smdn <smdn@smdn.jp>"

name: Run build integrity tests

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**/*.h'
      - 'src/**/*.hpp'
      - 'tests/test-build/**/*.cpp'

  pull_request:
    branches: [ main ]
    paths:
      - 'src/**/*.h'
      - 'src/**/*.hpp'
      - 'tests/test-build/**/*.cpp'

  workflow_dispatch:
    inputs:
      verbose:
        description: "If true, enables verbose output."
        required: false
        type: boolean
        default: false

jobs:
  test-build:
    name: Perform tests of the build integrity
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1

    - name: Setup caches
      uses: actions/cache@v4.3.0
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio

    - name: Install python
      uses: actions/setup-python@v6.0.0
      with:
        python-version: '3.12.3'

    - name: Install PlatformIO Core
      run: |
        # ref: https://docs.platformio.org/en/stable/integration/ci/github-actions.html#using-cmd-run-command
        pip install --upgrade platformio

    - name: Run tests
      shell: pwsh
      run: |
        # TODO: use pio run --silent
        $verbose = '${{ inputs.verbose }}' -ieq 'true'

        tests/test-build/run.sh